//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LAClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="UserList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="User")]
    [System.SerializableAttribute()]
    public class UserList : System.Collections.Generic.List<LAClient.ServiceReference1.User> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class User : LAClient.ServiceReference1.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LAClient.ServiceReference1.AreaCode AreaCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BirthDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Checked1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeviceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ext_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ext_TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LAClient.ServiceReference1.InterestList InterestsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsVerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastUpdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ManagerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LAClient.ServiceReference1.Preference PreferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SeenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LAClient.ServiceReference1.Sex SexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LAClient.ServiceReference1.ValueList ValuesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LAClient.ServiceReference1.AreaCode AreaCode {
            get {
                return this.AreaCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.AreaCodeField, value) != true)) {
                    this.AreaCodeField = value;
                    this.RaisePropertyChanged("AreaCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BirthDate {
            get {
                return this.BirthDateField;
            }
            set {
                if ((this.BirthDateField.Equals(value) != true)) {
                    this.BirthDateField = value;
                    this.RaisePropertyChanged("BirthDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Checked1 {
            get {
                return this.Checked1Field;
            }
            set {
                if ((this.Checked1Field.Equals(value) != true)) {
                    this.Checked1Field = value;
                    this.RaisePropertyChanged("Checked1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceID {
            get {
                return this.DeviceIDField;
            }
            set {
                if ((object.ReferenceEquals(this.DeviceIDField, value) != true)) {
                    this.DeviceIDField = value;
                    this.RaisePropertyChanged("DeviceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ext_Id {
            get {
                return this.Ext_IdField;
            }
            set {
                if ((object.ReferenceEquals(this.Ext_IdField, value) != true)) {
                    this.Ext_IdField = value;
                    this.RaisePropertyChanged("Ext_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ext_Type {
            get {
                return this.Ext_TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.Ext_TypeField, value) != true)) {
                    this.Ext_TypeField = value;
                    this.RaisePropertyChanged("Ext_Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fname {
            get {
                return this.FnameField;
            }
            set {
                if ((object.ReferenceEquals(this.FnameField, value) != true)) {
                    this.FnameField = value;
                    this.RaisePropertyChanged("Fname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Info {
            get {
                return this.InfoField;
            }
            set {
                if ((object.ReferenceEquals(this.InfoField, value) != true)) {
                    this.InfoField = value;
                    this.RaisePropertyChanged("Info");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LAClient.ServiceReference1.InterestList Interests {
            get {
                return this.InterestsField;
            }
            set {
                if ((object.ReferenceEquals(this.InterestsField, value) != true)) {
                    this.InterestsField = value;
                    this.RaisePropertyChanged("Interests");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsVer {
            get {
                return this.IsVerField;
            }
            set {
                if ((this.IsVerField.Equals(value) != true)) {
                    this.IsVerField = value;
                    this.RaisePropertyChanged("IsVer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUpdate {
            get {
                return this.LastUpdateField;
            }
            set {
                if ((this.LastUpdateField.Equals(value) != true)) {
                    this.LastUpdateField = value;
                    this.RaisePropertyChanged("LastUpdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lname {
            get {
                return this.LnameField;
            }
            set {
                if ((object.ReferenceEquals(this.LnameField, value) != true)) {
                    this.LnameField = value;
                    this.RaisePropertyChanged("Lname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Manager {
            get {
                return this.ManagerField;
            }
            set {
                if ((this.ManagerField.Equals(value) != true)) {
                    this.ManagerField = value;
                    this.RaisePropertyChanged("Manager");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LAClient.ServiceReference1.Preference Preference {
            get {
                return this.PreferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.PreferenceField, value) != true)) {
                    this.PreferenceField = value;
                    this.RaisePropertyChanged("Preference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Seen {
            get {
                return this.SeenField;
            }
            set {
                if ((this.SeenField.Equals(value) != true)) {
                    this.SeenField = value;
                    this.RaisePropertyChanged("Seen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LAClient.ServiceReference1.Sex Sex {
            get {
                return this.SexField;
            }
            set {
                if ((object.ReferenceEquals(this.SexField, value) != true)) {
                    this.SexField = value;
                    this.RaisePropertyChanged("Sex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LAClient.ServiceReference1.ValueList Values {
            get {
                return this.ValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.ValuesField, value) != true)) {
                    this.ValuesField = value;
                    this.RaisePropertyChanged("Values");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseEntity", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LAClient.ServiceReference1.AreaCode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LAClient.ServiceReference1.Interest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LAClient.ServiceReference1.Preference))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LAClient.ServiceReference1.Sex))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LAClient.ServiceReference1.Value))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LAClient.ServiceReference1.Friendship))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LAClient.ServiceReference1.FriendsMeeting))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LAClient.ServiceReference1.User))]
    public partial class BaseEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AreaCode", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class AreaCode : LAClient.ServiceReference1.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID1Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodeNum {
            get {
                return this.CodeNumField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeNumField, value) != true)) {
                    this.CodeNumField = value;
                    this.RaisePropertyChanged("CodeNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ID")]
        public int ID1 {
            get {
                return this.ID1Field;
            }
            set {
                if ((this.ID1Field.Equals(value) != true)) {
                    this.ID1Field = value;
                    this.RaisePropertyChanged("ID1");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Interest", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Interest : LAClient.ServiceReference1.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InterestNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ID")]
        public int ID1 {
            get {
                return this.ID1Field;
            }
            set {
                if ((this.ID1Field.Equals(value) != true)) {
                    this.ID1Field = value;
                    this.RaisePropertyChanged("ID1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InterestName {
            get {
                return this.InterestNameField;
            }
            set {
                if ((object.ReferenceEquals(this.InterestNameField, value) != true)) {
                    this.InterestNameField = value;
                    this.RaisePropertyChanged("InterestName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Preference", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Preference : LAClient.ServiceReference1.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PGenNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ID")]
        public int ID1 {
            get {
                return this.ID1Field;
            }
            set {
                if ((this.ID1Field.Equals(value) != true)) {
                    this.ID1Field = value;
                    this.RaisePropertyChanged("ID1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PGenName {
            get {
                return this.PGenNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PGenNameField, value) != true)) {
                    this.PGenNameField = value;
                    this.RaisePropertyChanged("PGenName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sex", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Sex : LAClient.ServiceReference1.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID1Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GenName {
            get {
                return this.GenNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GenNameField, value) != true)) {
                    this.GenNameField = value;
                    this.RaisePropertyChanged("GenName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ID")]
        public int ID1 {
            get {
                return this.ID1Field;
            }
            set {
                if ((this.ID1Field.Equals(value) != true)) {
                    this.ID1Field = value;
                    this.RaisePropertyChanged("ID1");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Value", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Value : LAClient.ServiceReference1.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ID")]
        public int ID1 {
            get {
                return this.ID1Field;
            }
            set {
                if ((this.ID1Field.Equals(value) != true)) {
                    this.ID1Field = value;
                    this.RaisePropertyChanged("ID1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValueName {
            get {
                return this.ValueNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueNameField, value) != true)) {
                    this.ValueNameField = value;
                    this.RaisePropertyChanged("ValueName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Friendship", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Friendship : LAClient.ServiceReference1.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Friend1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Friend2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool FriendsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RequestidField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Friend1 {
            get {
                return this.Friend1Field;
            }
            set {
                if ((this.Friend1Field.Equals(value) != true)) {
                    this.Friend1Field = value;
                    this.RaisePropertyChanged("Friend1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Friend2 {
            get {
                return this.Friend2Field;
            }
            set {
                if ((this.Friend2Field.Equals(value) != true)) {
                    this.Friend2Field = value;
                    this.RaisePropertyChanged("Friend2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Friends {
            get {
                return this.FriendsField;
            }
            set {
                if ((this.FriendsField.Equals(value) != true)) {
                    this.FriendsField = value;
                    this.RaisePropertyChanged("Friends");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ID")]
        public int ID1 {
            get {
                return this.ID1Field;
            }
            set {
                if ((this.ID1Field.Equals(value) != true)) {
                    this.ID1Field = value;
                    this.RaisePropertyChanged("ID1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Requestid {
            get {
                return this.RequestidField;
            }
            set {
                if ((this.RequestidField.Equals(value) != true)) {
                    this.RequestidField = value;
                    this.RaisePropertyChanged("Requestid");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FriendsMeeting", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class FriendsMeeting : LAClient.ServiceReference1.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Fid {
            get {
                return this.FidField;
            }
            set {
                if ((this.FidField.Equals(value) != true)) {
                    this.FidField = value;
                    this.RaisePropertyChanged("Fid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ID")]
        public int ID1 {
            get {
                return this.ID1Field;
            }
            set {
                if ((this.ID1Field.Equals(value) != true)) {
                    this.ID1Field = value;
                    this.RaisePropertyChanged("ID1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Time {
            get {
                return this.TimeField;
            }
            set {
                if ((this.TimeField.Equals(value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="InterestList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="Interest")]
    [System.SerializableAttribute()]
    public class InterestList : System.Collections.Generic.List<LAClient.ServiceReference1.Interest> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ValueList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="Value")]
    [System.SerializableAttribute()]
    public class ValueList : System.Collections.Generic.List<LAClient.ServiceReference1.Value> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="SexList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="Sex")]
    [System.SerializableAttribute()]
    public class SexList : System.Collections.Generic.List<LAClient.ServiceReference1.Sex> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="PreferenceList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="Preference")]
    [System.SerializableAttribute()]
    public class PreferenceList : System.Collections.Generic.List<LAClient.ServiceReference1.Preference> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="FriendshipList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="Friendship")]
    [System.SerializableAttribute()]
    public class FriendshipList : System.Collections.Generic.List<LAClient.ServiceReference1.Friendship> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="FriendsMeetingList", Namespace="http://schemas.datacontract.org/2004/07/Model", ItemName="FriendsMeeting")]
    [System.SerializableAttribute()]
    public class FriendsMeetingList : System.Collections.Generic.List<LAClient.ServiceReference1.FriendsMeeting> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveImage", ReplyAction="http://tempuri.org/IService1/SaveImageResponse")]
        void SaveImage(byte[] imageArray, string image);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveImage", ReplyAction="http://tempuri.org/IService1/SaveImageResponse")]
        System.Threading.Tasks.Task SaveImageAsync(byte[] imageArray, string image);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetImage", ReplyAction="http://tempuri.org/IService1/GetImageResponse")]
        byte[] GetImage(string image);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetImage", ReplyAction="http://tempuri.org/IService1/GetImageResponse")]
        System.Threading.Tasks.Task<byte[]> GetImageAsync(string image);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectAllUsers", ReplyAction="http://tempuri.org/IService1/SelectAllUsersResponse")]
        LAClient.ServiceReference1.UserList SelectAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectAllUsers", ReplyAction="http://tempuri.org/IService1/SelectAllUsersResponse")]
        System.Threading.Tasks.Task<LAClient.ServiceReference1.UserList> SelectAllUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserByID", ReplyAction="http://tempuri.org/IService1/GetUserByIDResponse")]
        LAClient.ServiceReference1.User GetUserByID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserByID", ReplyAction="http://tempuri.org/IService1/GetUserByIDResponse")]
        System.Threading.Tasks.Task<LAClient.ServiceReference1.User> GetUserByIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserByEmail", ReplyAction="http://tempuri.org/IService1/GetUserByEmailResponse")]
        LAClient.ServiceReference1.User GetUserByEmail(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserByEmail", ReplyAction="http://tempuri.org/IService1/GetUserByEmailResponse")]
        System.Threading.Tasks.Task<LAClient.ServiceReference1.User> GetUserByEmailAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckLogin", ReplyAction="http://tempuri.org/IService1/CheckLoginResponse")]
        LAClient.ServiceReference1.User CheckLogin(string em, string pw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckLogin", ReplyAction="http://tempuri.org/IService1/CheckLoginResponse")]
        System.Threading.Tasks.Task<LAClient.ServiceReference1.User> CheckLoginAsync(string em, string pw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserByGuid", ReplyAction="http://tempuri.org/IService1/GetUserByGuidResponse")]
        LAClient.ServiceReference1.User GetUserByGuid(System.Guid did);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserByGuid", ReplyAction="http://tempuri.org/IService1/GetUserByGuidResponse")]
        System.Threading.Tasks.Task<LAClient.ServiceReference1.User> GetUserByGuidAsync(System.Guid did);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegiserUser", ReplyAction="http://tempuri.org/IService1/RegiserUserResponse")]
        LAClient.ServiceReference1.User RegiserUser(LAClient.ServiceReference1.User us);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegiserUser", ReplyAction="http://tempuri.org/IService1/RegiserUserResponse")]
        System.Threading.Tasks.Task<LAClient.ServiceReference1.User> RegiserUserAsync(LAClient.ServiceReference1.User us);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateUser", ReplyAction="http://tempuri.org/IService1/UpdateUserResponse")]
        LAClient.ServiceReference1.User UpdateUser(LAClient.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateUser", ReplyAction="http://tempuri.org/IService1/UpdateUserResponse")]
        System.Threading.Tasks.Task<LAClient.ServiceReference1.User> UpdateUserAsync(LAClient.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveChanges", ReplyAction="http://tempuri.org/IService1/SaveChangesResponse")]
        void SaveChanges();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveChanges", ReplyAction="http://tempuri.org/IService1/SaveChangesResponse")]
        System.Threading.Tasks.Task SaveChangesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Insert", ReplyAction="http://tempuri.org/IService1/InsertResponse")]
        void Insert(LAClient.ServiceReference1.User s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Insert", ReplyAction="http://tempuri.org/IService1/InsertResponse")]
        System.Threading.Tasks.Task InsertAsync(LAClient.ServiceReference1.User s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteUser", ReplyAction="http://tempuri.org/IService1/DeleteUserResponse")]
        void DeleteUser(LAClient.ServiceReference1.User s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteUser", ReplyAction="http://tempuri.org/IService1/DeleteUserResponse")]
        System.Threading.Tasks.Task DeleteUserAsync(LAClient.ServiceReference1.User s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllSexes", ReplyAction="http://tempuri.org/IService1/GetAllSexesResponse")]
        LAClient.ServiceReference1.SexList GetAllSexes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllSexes", ReplyAction="http://tempuri.org/IService1/GetAllSexesResponse")]
        System.Threading.Tasks.Task<LAClient.ServiceReference1.SexList> GetAllSexesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSexByID", ReplyAction="http://tempuri.org/IService1/GetSexByIDResponse")]
        LAClient.ServiceReference1.Sex GetSexByID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSexByID", ReplyAction="http://tempuri.org/IService1/GetSexByIDResponse")]
        System.Threading.Tasks.Task<LAClient.ServiceReference1.Sex> GetSexByIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllPreferences", ReplyAction="http://tempuri.org/IService1/GetAllPreferencesResponse")]
        LAClient.ServiceReference1.PreferenceList GetAllPreferences();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllPreferences", ReplyAction="http://tempuri.org/IService1/GetAllPreferencesResponse")]
        System.Threading.Tasks.Task<LAClient.ServiceReference1.PreferenceList> GetAllPreferencesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPreferenceByID", ReplyAction="http://tempuri.org/IService1/GetPreferenceByIDResponse")]
        LAClient.ServiceReference1.Preference GetPreferenceByID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPreferenceByID", ReplyAction="http://tempuri.org/IService1/GetPreferenceByIDResponse")]
        System.Threading.Tasks.Task<LAClient.ServiceReference1.Preference> GetPreferenceByIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllRequestedByUser", ReplyAction="http://tempuri.org/IService1/GetAllRequestedByUserResponse")]
        LAClient.ServiceReference1.UserList GetAllRequestedByUser(LAClient.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllRequestedByUser", ReplyAction="http://tempuri.org/IService1/GetAllRequestedByUserResponse")]
        System.Threading.Tasks.Task<LAClient.ServiceReference1.UserList> GetAllRequestedByUserAsync(LAClient.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllFriendsByUser", ReplyAction="http://tempuri.org/IService1/GetAllFriendsByUserResponse")]
        LAClient.ServiceReference1.UserList GetAllFriendsByUser(LAClient.ServiceReference1.User u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllFriendsByUser", ReplyAction="http://tempuri.org/IService1/GetAllFriendsByUserResponse")]
        System.Threading.Tasks.Task<LAClient.ServiceReference1.UserList> GetAllFriendsByUserAsync(LAClient.ServiceReference1.User u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllFriendshipsByUser", ReplyAction="http://tempuri.org/IService1/GetAllFriendshipsByUserResponse")]
        LAClient.ServiceReference1.FriendshipList GetAllFriendshipsByUser(LAClient.ServiceReference1.User u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllFriendshipsByUser", ReplyAction="http://tempuri.org/IService1/GetAllFriendshipsByUserResponse")]
        System.Threading.Tasks.Task<LAClient.ServiceReference1.FriendshipList> GetAllFriendshipsByUserAsync(LAClient.ServiceReference1.User u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllMeetingsByUsers", ReplyAction="http://tempuri.org/IService1/GetAllMeetingsByUsersResponse")]
        LAClient.ServiceReference1.FriendsMeetingList GetAllMeetingsByUsers(LAClient.ServiceReference1.User user, LAClient.ServiceReference1.User user2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllMeetingsByUsers", ReplyAction="http://tempuri.org/IService1/GetAllMeetingsByUsersResponse")]
        System.Threading.Tasks.Task<LAClient.ServiceReference1.FriendsMeetingList> GetAllMeetingsByUsersAsync(LAClient.ServiceReference1.User user, LAClient.ServiceReference1.User user2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/OnMeetingNewAddress", ReplyAction="http://tempuri.org/IService1/OnMeetingNewAddressResponse")]
        LAClient.ServiceReference1.User OnMeetingNewAddress(LAClient.ServiceReference1.User Current, string Address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/OnMeetingNewAddress", ReplyAction="http://tempuri.org/IService1/OnMeetingNewAddressResponse")]
        System.Threading.Tasks.Task<LAClient.ServiceReference1.User> OnMeetingNewAddressAsync(LAClient.ServiceReference1.User Current, string Address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetNewFriedshipMeeting", ReplyAction="http://tempuri.org/IService1/SetNewFriedshipMeetingResponse")]
        void SetNewFriedshipMeeting(LAClient.ServiceReference1.User Current, LAClient.ServiceReference1.User Meetup);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetNewFriedshipMeeting", ReplyAction="http://tempuri.org/IService1/SetNewFriedshipMeetingResponse")]
        System.Threading.Tasks.Task SetNewFriedshipMeetingAsync(LAClient.ServiceReference1.User Current, LAClient.ServiceReference1.User Meetup);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeclineRequest", ReplyAction="http://tempuri.org/IService1/DeclineRequestResponse")]
        void DeclineRequest(LAClient.ServiceReference1.User Current, LAClient.ServiceReference1.User Requester);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeclineRequest", ReplyAction="http://tempuri.org/IService1/DeclineRequestResponse")]
        System.Threading.Tasks.Task DeclineRequestAsync(LAClient.ServiceReference1.User Current, LAClient.ServiceReference1.User Requester);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Friend", ReplyAction="http://tempuri.org/IService1/FriendResponse")]
        string Friend(LAClient.ServiceReference1.User user1, LAClient.ServiceReference1.User user2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Friend", ReplyAction="http://tempuri.org/IService1/FriendResponse")]
        System.Threading.Tasks.Task<string> FriendAsync(LAClient.ServiceReference1.User user1, LAClient.ServiceReference1.User user2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckFollowState", ReplyAction="http://tempuri.org/IService1/CheckFollowStateResponse")]
        string CheckFollowState(LAClient.ServiceReference1.User user, LAClient.ServiceReference1.User user2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckFollowState", ReplyAction="http://tempuri.org/IService1/CheckFollowStateResponse")]
        System.Threading.Tasks.Task<string> CheckFollowStateAsync(LAClient.ServiceReference1.User user, LAClient.ServiceReference1.User user2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : LAClient.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<LAClient.ServiceReference1.IService1>, LAClient.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SaveImage(byte[] imageArray, string image) {
            base.Channel.SaveImage(imageArray, image);
        }
        
        public System.Threading.Tasks.Task SaveImageAsync(byte[] imageArray, string image) {
            return base.Channel.SaveImageAsync(imageArray, image);
        }
        
        public byte[] GetImage(string image) {
            return base.Channel.GetImage(image);
        }
        
        public System.Threading.Tasks.Task<byte[]> GetImageAsync(string image) {
            return base.Channel.GetImageAsync(image);
        }
        
        public LAClient.ServiceReference1.UserList SelectAllUsers() {
            return base.Channel.SelectAllUsers();
        }
        
        public System.Threading.Tasks.Task<LAClient.ServiceReference1.UserList> SelectAllUsersAsync() {
            return base.Channel.SelectAllUsersAsync();
        }
        
        public LAClient.ServiceReference1.User GetUserByID(int id) {
            return base.Channel.GetUserByID(id);
        }
        
        public System.Threading.Tasks.Task<LAClient.ServiceReference1.User> GetUserByIDAsync(int id) {
            return base.Channel.GetUserByIDAsync(id);
        }
        
        public LAClient.ServiceReference1.User GetUserByEmail(string email) {
            return base.Channel.GetUserByEmail(email);
        }
        
        public System.Threading.Tasks.Task<LAClient.ServiceReference1.User> GetUserByEmailAsync(string email) {
            return base.Channel.GetUserByEmailAsync(email);
        }
        
        public LAClient.ServiceReference1.User CheckLogin(string em, string pw) {
            return base.Channel.CheckLogin(em, pw);
        }
        
        public System.Threading.Tasks.Task<LAClient.ServiceReference1.User> CheckLoginAsync(string em, string pw) {
            return base.Channel.CheckLoginAsync(em, pw);
        }
        
        public LAClient.ServiceReference1.User GetUserByGuid(System.Guid did) {
            return base.Channel.GetUserByGuid(did);
        }
        
        public System.Threading.Tasks.Task<LAClient.ServiceReference1.User> GetUserByGuidAsync(System.Guid did) {
            return base.Channel.GetUserByGuidAsync(did);
        }
        
        public LAClient.ServiceReference1.User RegiserUser(LAClient.ServiceReference1.User us) {
            return base.Channel.RegiserUser(us);
        }
        
        public System.Threading.Tasks.Task<LAClient.ServiceReference1.User> RegiserUserAsync(LAClient.ServiceReference1.User us) {
            return base.Channel.RegiserUserAsync(us);
        }
        
        public LAClient.ServiceReference1.User UpdateUser(LAClient.ServiceReference1.User user) {
            return base.Channel.UpdateUser(user);
        }
        
        public System.Threading.Tasks.Task<LAClient.ServiceReference1.User> UpdateUserAsync(LAClient.ServiceReference1.User user) {
            return base.Channel.UpdateUserAsync(user);
        }
        
        public void SaveChanges() {
            base.Channel.SaveChanges();
        }
        
        public System.Threading.Tasks.Task SaveChangesAsync() {
            return base.Channel.SaveChangesAsync();
        }
        
        public void Insert(LAClient.ServiceReference1.User s) {
            base.Channel.Insert(s);
        }
        
        public System.Threading.Tasks.Task InsertAsync(LAClient.ServiceReference1.User s) {
            return base.Channel.InsertAsync(s);
        }
        
        public void DeleteUser(LAClient.ServiceReference1.User s) {
            base.Channel.DeleteUser(s);
        }
        
        public System.Threading.Tasks.Task DeleteUserAsync(LAClient.ServiceReference1.User s) {
            return base.Channel.DeleteUserAsync(s);
        }
        
        public LAClient.ServiceReference1.SexList GetAllSexes() {
            return base.Channel.GetAllSexes();
        }
        
        public System.Threading.Tasks.Task<LAClient.ServiceReference1.SexList> GetAllSexesAsync() {
            return base.Channel.GetAllSexesAsync();
        }
        
        public LAClient.ServiceReference1.Sex GetSexByID(int id) {
            return base.Channel.GetSexByID(id);
        }
        
        public System.Threading.Tasks.Task<LAClient.ServiceReference1.Sex> GetSexByIDAsync(int id) {
            return base.Channel.GetSexByIDAsync(id);
        }
        
        public LAClient.ServiceReference1.PreferenceList GetAllPreferences() {
            return base.Channel.GetAllPreferences();
        }
        
        public System.Threading.Tasks.Task<LAClient.ServiceReference1.PreferenceList> GetAllPreferencesAsync() {
            return base.Channel.GetAllPreferencesAsync();
        }
        
        public LAClient.ServiceReference1.Preference GetPreferenceByID(int id) {
            return base.Channel.GetPreferenceByID(id);
        }
        
        public System.Threading.Tasks.Task<LAClient.ServiceReference1.Preference> GetPreferenceByIDAsync(int id) {
            return base.Channel.GetPreferenceByIDAsync(id);
        }
        
        public LAClient.ServiceReference1.UserList GetAllRequestedByUser(LAClient.ServiceReference1.User user) {
            return base.Channel.GetAllRequestedByUser(user);
        }
        
        public System.Threading.Tasks.Task<LAClient.ServiceReference1.UserList> GetAllRequestedByUserAsync(LAClient.ServiceReference1.User user) {
            return base.Channel.GetAllRequestedByUserAsync(user);
        }
        
        public LAClient.ServiceReference1.UserList GetAllFriendsByUser(LAClient.ServiceReference1.User u) {
            return base.Channel.GetAllFriendsByUser(u);
        }
        
        public System.Threading.Tasks.Task<LAClient.ServiceReference1.UserList> GetAllFriendsByUserAsync(LAClient.ServiceReference1.User u) {
            return base.Channel.GetAllFriendsByUserAsync(u);
        }
        
        public LAClient.ServiceReference1.FriendshipList GetAllFriendshipsByUser(LAClient.ServiceReference1.User u) {
            return base.Channel.GetAllFriendshipsByUser(u);
        }
        
        public System.Threading.Tasks.Task<LAClient.ServiceReference1.FriendshipList> GetAllFriendshipsByUserAsync(LAClient.ServiceReference1.User u) {
            return base.Channel.GetAllFriendshipsByUserAsync(u);
        }
        
        public LAClient.ServiceReference1.FriendsMeetingList GetAllMeetingsByUsers(LAClient.ServiceReference1.User user, LAClient.ServiceReference1.User user2) {
            return base.Channel.GetAllMeetingsByUsers(user, user2);
        }
        
        public System.Threading.Tasks.Task<LAClient.ServiceReference1.FriendsMeetingList> GetAllMeetingsByUsersAsync(LAClient.ServiceReference1.User user, LAClient.ServiceReference1.User user2) {
            return base.Channel.GetAllMeetingsByUsersAsync(user, user2);
        }
        
        public LAClient.ServiceReference1.User OnMeetingNewAddress(LAClient.ServiceReference1.User Current, string Address) {
            return base.Channel.OnMeetingNewAddress(Current, Address);
        }
        
        public System.Threading.Tasks.Task<LAClient.ServiceReference1.User> OnMeetingNewAddressAsync(LAClient.ServiceReference1.User Current, string Address) {
            return base.Channel.OnMeetingNewAddressAsync(Current, Address);
        }
        
        public void SetNewFriedshipMeeting(LAClient.ServiceReference1.User Current, LAClient.ServiceReference1.User Meetup) {
            base.Channel.SetNewFriedshipMeeting(Current, Meetup);
        }
        
        public System.Threading.Tasks.Task SetNewFriedshipMeetingAsync(LAClient.ServiceReference1.User Current, LAClient.ServiceReference1.User Meetup) {
            return base.Channel.SetNewFriedshipMeetingAsync(Current, Meetup);
        }
        
        public void DeclineRequest(LAClient.ServiceReference1.User Current, LAClient.ServiceReference1.User Requester) {
            base.Channel.DeclineRequest(Current, Requester);
        }
        
        public System.Threading.Tasks.Task DeclineRequestAsync(LAClient.ServiceReference1.User Current, LAClient.ServiceReference1.User Requester) {
            return base.Channel.DeclineRequestAsync(Current, Requester);
        }
        
        public string Friend(LAClient.ServiceReference1.User user1, LAClient.ServiceReference1.User user2) {
            return base.Channel.Friend(user1, user2);
        }
        
        public System.Threading.Tasks.Task<string> FriendAsync(LAClient.ServiceReference1.User user1, LAClient.ServiceReference1.User user2) {
            return base.Channel.FriendAsync(user1, user2);
        }
        
        public string CheckFollowState(LAClient.ServiceReference1.User user, LAClient.ServiceReference1.User user2) {
            return base.Channel.CheckFollowState(user, user2);
        }
        
        public System.Threading.Tasks.Task<string> CheckFollowStateAsync(LAClient.ServiceReference1.User user, LAClient.ServiceReference1.User user2) {
            return base.Channel.CheckFollowStateAsync(user, user2);
        }
    }
}
